# Generated by Django 4.2.6 on 2024-11-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fipleapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="subject_id",
            new_name="subject",
        ),
    ]
