# Generated by Django 5.1.1 on 2025-01-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/back/', verbose_name='裏画像'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/front/', verbose_name='表画像'),
        ),
    ]
