# Generated by Django 4.2.6 on 2024-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fipleapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_delivery_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="secound_delivery_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="third_delivery_address",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.TextField(default="", max_length=128),
        ),
    ]
