# Generated by Django 5.1.1 on 2025-01-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0002_alter_product_back_image_alter_product_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_position',
            field=models.CharField(choices=[('頭', 'Head'), ('上半身', 'Upper Body'), ('下半身', 'Lower Body'), ('足', 'Foot')], default='頭', max_length=10),
        ),
    ]
