# Generated by Django 4.2.6 on 2024-10-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fipleapp", "0002_remove_customuser_first_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.TextField(default="", max_length=128, null=True),
        ),
    ]
