# Generated by Django 4.2.6 on 2024-11-11 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=254)),
                ('review_detail', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(1, '1☆'), (2, '2☆'), (3, '3☆'), (4, '4☆'), (5, '5☆')], default=5)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fipleapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
