# Generated by Django 5.1.1 on 2024-11-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0004_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
