# Generated by Django 5.1.1 on 2024-10-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
