# Generated by Django 4.2.6 on 2024-11-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0005_contactcategory_questioncategory_faq_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
