# Generated by Django 4.2.6 on 2024-12-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0006_size_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
