# Generated by Django 5.1.1 on 2024-11-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('注文受付', '注文受付'), ('支払い完了', '支払い完了'), ('発送済み', '発送済み'), ('配達完了', '配達完了'), ('キャンセル', 'キャンセル')], default='支払い完了', max_length=20),
        ),
    ]
