# Generated by Django 5.1.1 on 2024-11-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipleapp', '0009_paymentsession_pricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsession',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_origin', 'color', 'size'), name='unique_product_combination'),
        ),
        migrations.DeleteModel(
            name='PaymentSession',
        ),
    ]
